#!/usr/bin/env python3
"""
Information-theoretic payload discriminator for the Voynich "machine".

Question: after fitting the BEST mechanical model, does the manuscript retain an
irreducible residual "payload" (a real message run through a verbose cipher),
or does the machine essentially EXHAUST the text (self-generation)?

Method: held-out cross-entropy by physical-folio K-fold CV, applied by an
IDENTICAL pipeline to three corpora:
  (A) REAL manuscript
  (B) SELF-GEN floor  (corpora generated by the fitted machine)
  (C) CIPHER ceiling  (real English prose run through a verbose homophonic
                       cipher matched to the manuscript's marginals)

Read-only over the factorization TSV. All output stays under payload_mdl/.
numpy only, no GPU. Seeded.
"""
import csv, math, json, os, collections, random
import numpy as np

from pathlib import Path
RELEASE_ROOT = Path(__file__).resolve().parents[2]       # PUBLIC_RELEASE
FULL = str(RELEASE_ROOT / "data" / "factorization" / "full_surface_factorization.tsv")
OUT = str(Path(__file__).resolve().parent)               # payload_mdl/
os.makedirs(OUT, exist_ok=True)
SEED = 20260930
ROOT = str(RELEASE_ROOT)                                 # back-compat alias
# Public-domain English natural-language control (the "message ceiling" source).
ENGLISH_CONTROL = str(RELEASE_ROOT / "analysis" / "controls" / "english_jqadams.txt")

MULTI = ("cth", "ckh", "cph", "cfh", "ch", "sh")
BOS = "<s>"     # word-start pad
EOW = "</w>"    # word-end marker (a predicted symbol)


def glyph_tok(word):
    out, c = [], 0
    while c < len(word):
        u = next((g for g in MULTI if word.startswith(g, c)), None)
        if u:
            out.append(u); c += len(u)
        else:
            out.append(word[c]); c += 1
    return out


def parse_mol(s):
    if "=>" in s:
        body, state = s.rsplit("=>", 1)
    else:
        body, state = s, ""
    body = body.strip()
    return ("" if body in ("<EMPTY>", "") else body), state.strip()


# ----------------------------------------------------------------- load ----
def load():
    rows = []
    with open(FULL, encoding="utf-8") as f:
        for d in csv.DictReader(f, delimiter="\t"):
            rid = d["record_id"]; left, _, pos = rid.partition(":")
            folio, _, line = left.rpartition(".")
            body, state = parse_mol(d["symbolic_factor"])
            rows.append(dict(
                folio=folio or d["folio"], line=line,
                pos=int(pos) if pos.isdigit() else 0,
                surface=d["surface"], mol=d["symbolic_factor"].strip(),
                body=body, state=state,
                glyphs=tuple(glyph_tok(d["surface"])),
            ))
    rows.sort(key=lambda r: (r["folio"], _lnum(r["line"]), r["pos"]))
    return rows


def _lnum(s):
    try:
        return int(s)
    except Exception:
        return s


# A "corpus" is a list of lines. Each line = dict(folio=..., words=[word,...])
# where a word = dict(glyphs=tuple, mol=str). This lets the SAME pipeline run
# on real and synthetic data.
def rows_to_corpus(rows):
    lines = collections.OrderedDict()
    for r in rows:
        key = (r["folio"], r["line"])
        lines.setdefault(key, dict(folio=r["folio"], words=[]))
        lines[key]["words"].append(dict(glyphs=r["glyphs"], mol=r["mol"]))
    return list(lines.values())


# ------------------------------------------------ Witten-Bell n-gram -------
class GlyphNGram:
    """Interpolated Witten-Bell glyph model. A word = g1..gL, EOW. Context is
    the previous `order` glyphs within the word (BOS-padded). Parameter-free
    smoothing so the identical pipeline is unbiased across corpora."""

    def __init__(self, order):
        self.order = order

    def fit(self, corpus_lines):
        self.ctx = [collections.defaultdict(collections.Counter)
                    for _ in range(self.order + 1)]
        self.vocab = set([EOW])
        for ln in corpus_lines:
            for w in ln["words"]:
                seq = list(w["glyphs"]) + [EOW]
                self.vocab.update(w["glyphs"])
                hist = [BOS] * self.order
                for g in seq:
                    for k in range(self.order + 1):
                        c = tuple(hist[len(hist) - k:]) if k else ()
                        self.ctx[k][c][g] += 1
                    hist = (hist + [g])[1:] if self.order else hist
        self.V = len(self.vocab) + 1  # +1 for UNK glyph mass
        # precompute per-context totals & distinct counts
        self._tot = [
            {c: sum(cnt.values()) for c, cnt in self.ctx[k].items()}
            for k in range(self.order + 1)
        ]
        self._dist = [
            {c: len(cnt) for c, cnt in self.ctx[k].items()}
            for k in range(self.order + 1)
        ]
        return self

    def _p0(self, g):
        cnt = self.ctx[0][()]
        N = self._tot[0][()]
        Dtypes = self._dist[0][()]
        lam = N / (N + Dtypes) if (N + Dtypes) else 0.0
        mle = cnt.get(g, 0) / N if N else 0.0
        return lam * mle + (1 - lam) * (1.0 / self.V)

    def prob(self, g, hist):
        p = self._p0(g)
        for k in range(1, self.order + 1):
            c = tuple(hist[len(hist) - k:])
            cnt = self.ctx[k].get(c)
            if not cnt:
                continue
            N = self._tot[k][c]
            D = self._dist[k][c]
            lam = N / (N + D)
            mle = cnt.get(g, 0) / N
            p = lam * mle + (1 - lam) * p
        return p

    def word_bits(self, glyphs):
        """-log2 P(word) summed over its glyphs + EOW; also returns #events."""
        hist = [BOS] * self.order
        bits = 0.0
        seq = list(glyphs) + [EOW]
        for g in seq:
            p = self.prob(g, hist)
            bits += -math.log2(max(p, 1e-300))
            hist = (hist + [g])[1:] if self.order else hist
        return bits, len(seq)

    def sample_word(self, rng, maxlen=20):
        hist = [BOS] * self.order
        out = []
        vocab = list(self.vocab)
        for _ in range(maxlen):
            ps = np.array([self.prob(g, hist) for g in vocab])
            ps = ps / ps.sum()
            g = vocab[rng.choice(len(vocab), p=ps)]
            if g == EOW:
                break
            out.append(g)
            hist = (hist + [g])[1:] if self.order else hist
        return tuple(out)


# ------------------------------------------------ word-level models --------
class MolUnigram:
    """Molecule unigram with backoff to a glyph spelling model for OOV words."""

    def __init__(self, glyph_backoff, mix=0.0):
        self.gb = glyph_backoff      # a fitted GlyphNGram
        self.mix = mix               # kept for API symmetry

    def fit(self, corpus_lines):
        self.gb.fit(corpus_lines)
        self.count = collections.Counter()
        for ln in corpus_lines:
            for w in ln["words"]:
                self.count[w["mol"]] += 1
        self.N = sum(self.count.values())
        self.Dtypes = len(self.count)
        return self

    def word_bits(self, w):
        # Witten-Bell style interpolation of the word cache with the spelling model
        c = self.count.get(w["mol"], 0)
        lam = self.N / (self.N + self.Dtypes) if self.N else 0.0
        p_cache = c / self.N if self.N else 0.0
        gb_bits, ev = self.gb.word_bits(w["glyphs"])
        p_spell = 2 ** (-gb_bits)
        p = lam * p_cache + (1 - lam) * p_spell
        return -math.log2(max(p, 1e-300)), ev


class MolBigram:
    """Molecule bigram (within-line Markov-1) backing off to unigram then the
    glyph spelling model. Captures local word-to-word copying."""

    def __init__(self, glyph_backoff):
        self.gb = glyph_backoff

    def fit(self, corpus_lines):
        self.gb.fit(corpus_lines)
        self.bi = collections.defaultdict(collections.Counter)
        self.uni = collections.Counter()
        for ln in corpus_lines:
            prev = BOS
            for w in ln["words"]:
                self.bi[prev][w["mol"]] += 1
                self.uni[w["mol"]] += 1
                prev = w["mol"]
        self.N = sum(self.uni.values())
        self.Duni = len(self.uni)
        return self

    def word_bits(self, w, prev):
        gb_bits, ev = self.gb.word_bits(w["glyphs"])
        p_spell = 2 ** (-gb_bits)
        # unigram level
        lam_u = self.N / (self.N + self.Duni) if self.N else 0.0
        p_uni = lam_u * (self.uni.get(w["mol"], 0) / self.N if self.N else 0) \
            + (1 - lam_u) * p_spell
        # bigram level
        cnt = self.bi.get(prev)
        if cnt:
            Nb = sum(cnt.values()); Db = len(cnt)
            lam_b = Nb / (Nb + Db)
            p = lam_b * (cnt.get(w["mol"], 0) / Nb) + (1 - lam_b) * p_uni
        else:
            p = p_uni
        return -math.log2(max(p, 1e-300)), ev


# ------------------------------------------------ CV harness ---------------
def folds_by_folio(corpus_lines, k, seed):
    folios = sorted({ln["folio"] for ln in corpus_lines})
    random.Random(seed).shuffle(folios)
    return [set(folios[i::k]) for i in range(k)]


def eval_corpus(corpus_lines, models, k=5, seed=SEED):
    """models: dict name-> ('glyph',order) | ('mol1',) | ('mol2',). Returns per
    model: list of per-fold (bits_token, bits_glyph, n_words, n_events)."""
    assign = folds_by_folio(corpus_lines, k, seed)
    res = {name: [] for name in models}
    for heldout in assign:
        train = [ln for ln in corpus_lines if ln["folio"] not in heldout]
        test = [ln for ln in corpus_lines if ln["folio"] in heldout]
        for name, spec in models.items():
            if spec[0] == "glyph":
                m = GlyphNGram(spec[1]).fit(train)
                bits = 0.0; ev = 0; nw = 0
                for ln in test:
                    for w in ln["words"]:
                        b, e = m.word_bits(w["glyphs"])
                        bits += b; ev += e; nw += 1
            elif spec[0] == "mol1":
                m = MolUnigram(GlyphNGram(spec[1])).fit(train)
                bits = 0.0; ev = 0; nw = 0
                for ln in test:
                    for w in ln["words"]:
                        b, e = m.word_bits(w)
                        bits += b; ev += e; nw += 1
            elif spec[0] == "mol2":
                m = MolBigram(GlyphNGram(spec[1])).fit(train)
                bits = 0.0; ev = 0; nw = 0
                for ln in test:
                    prev = BOS
                    for w in ln["words"]:
                        b, e = m.word_bits(w, prev)
                        bits += b; ev += e; nw += 1
                        prev = w["mol"]
            res[name].append((bits / nw, bits / ev, nw, ev))
    return res


def summarize(res):
    out = {}
    for name, folds in res.items():
        bt = np.array([f[0] for f in folds])
        bg = np.array([f[1] for f in folds])
        nw = np.array([f[2] for f in folds], float)
        # weighted mean across folds; fold sd for CI (t, df=k-1)
        mt = np.average(bt, weights=nw)
        mg = np.average(bg, weights=nw)
        sdt = bt.std(ddof=1); sdg = bg.std(ddof=1)
        tcrit = 2.776  # t_.975, df=4 (5-fold)
        out[name] = dict(
            bits_token=float(mt), bits_glyph=float(mg),
            bt_fold_sd=float(sdt), bg_fold_sd=float(sdg),
            bt_ci=float(tcrit * sdt / math.sqrt(len(bt))),
            bg_ci=float(tcrit * sdg / math.sqrt(len(bg))),
            n_words=int(nw.sum()),
        )
    return out


if __name__ == "__main__":
    rows = load()
    corpus = rows_to_corpus(rows)
    nglyph = sum(len(w["glyphs"]) + 1 for ln in corpus for w in ln["words"])
    nword = sum(len(ln["words"]) for ln in corpus)
    print(f"corpus: {len(corpus)} lines, {nword} words, {nglyph} glyph-events "
          f"({nglyph/nword:.2f} events/word)")
    # sanity: glyph_tok(surface) interior vs stored body
    ok = 0; tot = 0
    for r in rows[:2000]:
        tot += 1
        interior = " ".join(r["glyphs"][1:-1]) if len(r["glyphs"]) >= 2 else ""
        if interior == r["body"]:
            ok += 1
    print(f"surface-tokenization vs stored body match: {ok}/{tot}")

    models = {
        "glyph0": ("glyph", 0), "glyph1": ("glyph", 1),
        "glyph2": ("glyph", 2), "glyph3": ("glyph", 3),
        "mol_uni(spell3)": ("mol1", 3),
        "mol_bi(spell3)": ("mol2", 3),
    }
    res = eval_corpus(corpus, models)
    summ = summarize(res)
    print("\n=== REAL manuscript held-out (5-fold by folio) ===")
    print(f"{'model':20s} {'bits/token':>12s} {'±CI':>7s} {'bits/glyph':>12s} {'±CI':>7s}")
    for name in models:
        s = summ[name]
        print(f"{name:20s} {s['bits_token']:12.3f} {s['bt_ci']:7.3f} "
              f"{s['bits_glyph']:12.3f} {s['bg_ci']:7.3f}")
    json.dump({"real": summ,
               "corpus": dict(lines=len(corpus), words=nword, glyph_events=nglyph)},
              open(OUT + "/real_ladder.json", "w"), indent=2)
    print("\nwrote real_ladder.json")
