#!/usr/bin/env python3
"""
Meaning-free generators for the Montemurro null battery.

All produce a stream of TOKEN STRINGS of a target length N, in positional order.
We then overlay the REAL manuscript's part labels (section / A-B / positional
blocks) BY POSITION -- the generator never sees a section label.

FLOOR generators (no drift, section-blind, stationary):
  - iid_bag      : draw each token i.i.d. from the real token unigram.
  - markov1_tok  : 1st-order Markov over real token types (global transitions).
Both are stationary -> their token composition does not vary with position ->
they are the "no-drift floor": section-MI should collapse to the shuffle floor.

DRIFT generator (Timm-Schinner style self-citation, meaning-free):
  - copy+mutate from a recency window over already-emitted STRINGS, with rare
    glyph-level innovation. Drift/localization EMERGES from copying (a string
    that appears or is mutated into existence near position t can only be copied
    within ~window of t, and copy-of-copy chains extend that), NOT from any
    section label. Innovations are generated by a 1st-order GLYPH Markov (fit to
    the real glyph-bigram stats) so novel strings are realistic and the type
    inventory is unbounded (needed to match TTR/hapax). Mutations are single
    glyph edits -> local near-neighbour vocabulary.

Calibration knobs (fit to MECHANICAL stats only, never to section-MI):
  p_new  : innovation rate       -> governs type count / TTR / drift strength
  p_mut  : mutation rate on copy  -> governs exact-repeat rate / hapax / near-dupes
  window : recency window (memory)-> governs the SCALE of drift (swept, not fit to sections)
"""
import collections, math
import numpy as np

# EVA multi-glyph tokens (project tokenizer, per shadow_of_null): match these first.
MULTI = ["cth", "ckh", "cph", "cfh", "ch", "sh"]


def tokenize_glyphs(s):
    """Greedy multi-glyph tokenization of an EVA surface string."""
    i = 0
    out = []
    n = len(s)
    while i < n:
        matched = None
        for m in MULTI:
            if s.startswith(m, i):
                matched = m
                break
        if matched:
            out.append(matched)
            i += len(matched)
        else:
            out.append(s[i])
            i += 1
    return out


def fit_glyph_markov(strings):
    """1st-order glyph Markov with START(^) and END($) over multi-glyph tokens."""
    trans = collections.defaultdict(collections.Counter)
    for s in strings:
        g = ["^"] + tokenize_glyphs(s) + ["$"]
        for a, b in zip(g[:-1], g[1:]):
            trans[a][b] += 1
    # precompute sampling tables
    table = {}
    for a, c in trans.items():
        items = list(c.items())
        syms = [x[0] for x in items]
        probs = np.array([x[1] for x in items], dtype=float)
        probs /= probs.sum()
        table[a] = (syms, probs)
    return table


def sample_glyph_markov(table, rng, max_len=25):
    cur = "^"
    out = []
    for _ in range(max_len):
        if cur not in table:
            break
        syms, probs = table[cur]
        cur = syms[rng.choice(len(syms), p=probs)]
        if cur == "$":
            break
        out.append(cur)
    return "".join(out)


def mutate_string(s, table, rng):
    """One single-glyph edit (substitute / insert / delete) on the glyph-token seq."""
    g = tokenize_glyphs(s)
    if not g:
        return sample_glyph_markov(table, rng)
    op = rng.integers(3)
    pos = int(rng.integers(len(g)))
    # a random glyph drawn from the marginal glyph inventory
    if op == 0:  # substitute
        g[pos] = _rand_glyph(table, rng)
    elif op == 1:  # insert
        g.insert(pos, _rand_glyph(table, rng))
    else:  # delete
        if len(g) > 1:
            g.pop(pos)
        else:
            g[pos] = _rand_glyph(table, rng)
    return "".join(g)


_GLYPH_CACHE = {}


def _rand_glyph(table, rng):
    key = id(table)
    if key not in _GLYPH_CACHE:
        # marginal over all successor glyphs (excluding END)
        c = collections.Counter()
        for a, (syms, probs) in table.items():
            for s, p in zip(syms, probs):
                if s != "$":
                    c[s] += p
        syms = list(c.keys())
        probs = np.array([c[s] for s in syms], float)
        probs /= probs.sum()
        _GLYPH_CACHE[key] = (syms, probs)
    syms, probs = _GLYPH_CACHE[key]
    return syms[rng.choice(len(syms), p=probs)]


# --------------------------------------------------------------- generators --
def gen_iid_bag(real_tokens, rng):
    toks = list(real_tokens)
    N = len(toks)
    c = collections.Counter(toks)
    types = list(c.keys())
    probs = np.array([c[t] for t in types], float)
    probs /= probs.sum()
    idx = rng.choice(len(types), size=N, p=probs)
    return [types[i] for i in idx]


def gen_markov1_tok(real_tokens, rng):
    """1st-order Markov over token types, global transitions, matched length,
    START distribution = real first-token-of-line marginal approximated by global
    unigram start (we just start from unigram)."""
    N = len(real_tokens)
    trans = collections.defaultdict(collections.Counter)
    for a, b in zip(real_tokens[:-1], real_tokens[1:]):
        trans[a][b] += 1
    c = collections.Counter(real_tokens)
    types = list(c.keys())
    uni_p = np.array([c[t] for t in types], float)
    uni_p /= uni_p.sum()
    tbl = {}
    for a, cc in trans.items():
        items = list(cc.items())
        syms = [x[0] for x in items]
        pr = np.array([x[1] for x in items], float)
        pr /= pr.sum()
        tbl[a] = (syms, pr)
    out = []
    cur = types[rng.choice(len(types), p=uni_p)]
    out.append(cur)
    for _ in range(N - 1):
        if cur in tbl:
            syms, pr = tbl[cur]
            cur = syms[rng.choice(len(syms), p=pr)]
        else:
            cur = types[rng.choice(len(types), p=uni_p)]
        out.append(cur)
    return out


def gen_self_citation(N, innovate, mutate, rng, p_new, p_mut, window):
    """Timm-Schinner style copy+mutate with recency window + innovation.
    innovate(rng)->str ; mutate(str,rng)->str  encapsulate the layer (surface/molecule)."""
    out = []
    u_new = rng.random(N)
    u_mut = rng.random(N)
    for i in range(N):
        if i == 0 or u_new[i] < p_new:
            w = innovate(rng)
            if w == "":
                w = innovate(rng)
        else:
            k = 1 + int(rng.integers(min(i, window)))
            src = out[i - k]
            w = mutate(src, rng) if u_mut[i] < p_mut else src
        out.append(w if w != "" else "o")
    return out


# ---- surface closures ----
def surface_closures(real_surface):
    table = fit_glyph_markov(real_surface)
    return (lambda rng: sample_glyph_markov(table, rng),
            lambda s, rng: mutate_string(s, table, rng))


# ---- molecule builders (body glyph-tokens + separate state channel) ----
def parse_mol(s):
    if "=>" in s:
        body, state = s.rsplit("=>", 1)
    else:
        body, state = s, ""
    body = body.strip()
    toks = [] if body in ("<EMPTY>", "") else body.split()
    return toks, state.strip()


def fit_mol_model(real_mol):
    """1st-order Markov over BODY glyph-tokens (^/$), + marginal over states."""
    trans = collections.defaultdict(collections.Counter)
    states = collections.Counter()
    for s in real_mol:
        toks, st = parse_mol(s)
        states[st] += 1
        g = ["^"] + toks + ["$"]
        for a, b in zip(g[:-1], g[1:]):
            trans[a][b] += 1
    table = {}
    for a, c in trans.items():
        items = list(c.items())
        syms = [x[0] for x in items]
        pr = np.array([x[1] for x in items], float)
        pr /= pr.sum()
        table[a] = (syms, pr)
    st_syms = list(states.keys())
    st_pr = np.array([states[s] for s in st_syms], float)
    st_pr /= st_pr.sum()
    body_marg = _body_marginal(table)
    return dict(table=table, st_syms=st_syms, st_pr=st_pr, body_marg=body_marg)


def _body_marginal(table):
    c = collections.Counter()
    for a, (syms, probs) in table.items():
        for s, p in zip(syms, probs):
            if s != "$":
                c[s] += p
    syms = list(c.keys())
    pr = np.array([c[s] for s in syms], float)
    pr /= pr.sum()
    return (syms, pr)


def _sample_body(table, rng, max_len=12):
    cur = "^"
    out = []
    for _ in range(max_len):
        if cur not in table:
            break
        syms, pr = table[cur]
        cur = syms[rng.choice(len(syms), p=pr)]
        if cur == "$":
            break
        out.append(cur)
    return out


def _join_mol(toks, st):
    body = " ".join(toks) if toks else "<EMPTY>"
    return f"{body}=>{st}"


def mol_closures(real_mol):
    m = fit_mol_model(real_mol)
    table, st_syms, st_pr, body_marg = m['table'], m['st_syms'], m['st_pr'], m['body_marg']

    def innovate(rng):
        toks = _sample_body(table, rng)
        st = st_syms[rng.choice(len(st_syms), p=st_pr)]
        return _join_mol(toks, st)

    def mutate(s, rng):
        toks, st = parse_mol(s)
        op = rng.integers(4)
        if op == 3:  # flip state
            st = st_syms[rng.choice(len(st_syms), p=st_pr)]
            return _join_mol(toks, st)
        if not toks:
            toks = _sample_body(table, rng)
            return _join_mol(toks, st)
        syms, pr = body_marg
        pos = int(rng.integers(len(toks)))
        if op == 0:      # substitute body token
            toks[pos] = syms[rng.choice(len(syms), p=pr)]
        elif op == 1:    # insert
            toks.insert(pos, syms[rng.choice(len(syms), p=pr)])
        else:            # delete
            if len(toks) > 1:
                toks.pop(pos)
            else:
                toks[pos] = syms[rng.choice(len(syms), p=pr)]
        return _join_mol(toks, st)

    return innovate, mutate
